name: Deploy Wei to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Inject Hugging Face API Key
        run: echo "window.HF_API_KEY = '${{ secrets.HF_API_KEY }}';" > public/api-key.js

      - name: Show api-key.js content
        run: cat public/api-key.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
